config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins #define os recursos de get, post, put, delete, todos de uma vez

  root to:"welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :create, :edit, :update]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "A moeda foi adicionada à carteira com sucesso." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Moeda atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Moeda apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso Ruby on Rails"
    @nome = params[:nome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def locale
        if I18n.locale == :en
            "U.S English"
        else
            "Português brasileiro"
        end
    end

    def data_br(data_us)
        data_us.strftime("%d/%m/%Y")
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
</table>
<div id="<%= dom_id coin %>">
<table class="table table-hover">
    <thead>
      <tr>
      <th><%= Coin.human_attribute_name(:description) %></th>
      <th><%= Coin.human_attribute_name(:acronym) %></th>
      <th><%= Coin.human_attribute_name(:url_image) %></th>
      <th><%= Coin.human_attribute_name(:mining_type) %></th>
      </tr>
    </thead>
    </tbody>
    <tr>
      <td><%= coin.description %></td>
      <td><%= coin.acronym %></td>
      <td><%= image_tag coin.url_image, size: "25x25"%></td>
      <td><%= coin.mining_type.description%></td>
      <td><%= link_to t('links.show'), coin %></td>
      </tr>
    </tbody>

  </table>
  </div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>
  
  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

  <div>
    <%= form.label :mining_type_id, style: "display: block" %>
    <%= form.select("mining_type_id", @mining_type_options) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('links.show'), @coin %> |
  <%= link_to t('links.walletback'), coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="h100 p-5 bg-light rounded-3">
<h1><%= t('links.coins')%></h1>
  <div id="coins">
  
    <% @coins.each do |coin| %>
      <%= render coin %>
    <% end %>
  </div>
  
</div>

<%= link_to t('links.new'), new_coin_path %> |
<%= link_to t('links.home'), welcome_index_path %>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('links.walletback'), coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to t('links.edit'), edit_coin_path(@coin) %> |
  <%= link_to t('links.walletback'), coins_path %>

  <%= button_to t('links.delete'), @coin, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptowallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <div class="container">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to 'Português', root_path(locale: 'pt-BR'), class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'English', root_path(locale: 'en'), class:"nav-link"%>
        </li>
      </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/coin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptowallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <table class="table table-hover">
    <thead>
      <tr>
      <th><%= MiningType.human_attribute_name(:description) %></th>
      <th><%= MiningType.human_attribute_name(:acronym) %></th>
      </tr>
    </thead>
    </tbody>
    <tr>
      <td><%= mining_type.description %></td>
      <td><%= mining_type.acronym %></td>
      <td><%= link_to t('links.showminingtype'), mining_type %></td>
      </tr>
    </tbody>

  </table>
</div>

app/views/mining_types/edit.html.erb
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to t('links.showminingtype'), @mining_type %> |
  <%= link_to t('links.miningtypesback'), mining_types_path %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mining types</h1>

<div id="mining_types">
  
    <% @mining_types.each do |mining_type| %>
      <%= render mining_type %>
    <% end %>
  
</div>

<%= link_to t('links.newminingtype'), new_mining_type_path %> |
<%= link_to t('links.home'), welcome_index_path %>

app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to t('links.miningtypesback'), mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to t('links.edit'), edit_mining_type_path(@mining_type) %> |
  <%= link_to t('links.miningtypesback'), mining_types_path %>

  <%= button_to t('links.delete'), @mining_type, method: :delete %>
</div>

app/views/welcome/_menu.html.erb
    <%= link_to t('links.walleteditor'), coins_path, class:"btn btn-dark btn-sm", role:"button" %>
    <%= link_to t('links.miningtypeeditor'), mining_types_path, class:"btn btn-dark btn-sm", role:"button" %>

app/views/welcome/index.html.erb
<div class="h100 p-5 bg-light rounded-3">

  <h1 class="display-4">Seja Bem-Vindo!</h1>
  <p class="lead">Olá, me chamo Igor e estou desenvolvendo esta aplicação Web, como trabalho prático do curso de Ruby on Rails da Udemy.</p>
  <hr class="my-4">
  <p>O objetivo dessa aplicação será um simulador de carteira de criptomoedas, onde o usuário poderá: Adicionar, excluir e editar sua carteira, com preço de entrada, a aplicação irá buscar o preço atual e retornará os lucros ou perdas do usuário.</p>
  <p class="lead">
  <%= render "menu" %>
  </p>

</div>
<p> <strong>Data de acesso:</strong> <%= I18n.l(Date.today) %></p>
<p>Idioma padrão: <strong><%= t('actual_locale') %></strong></p>